server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dunshop?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mybatis:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8


  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dundunteam.entity
  configuration:
#开启驼峰命名
    map-underscore-to-camel-case: true



